artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: your_data_source
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  training_data: artifacts/data_ingestion/CT-KIDNEY-DATASET-ORGANIZED  # UPDATED!
  params_epochs: 50
  params_batch_size: 16
  params_is_augmentation: True


evaluation:
  root_dir: artifacts/evaluation
  model_path: artifacts/training/model.h5
  test_data_dir: artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone







